# Generated by Django 3.2.15 on 2022-09-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firingtickets', '0002_project_potter'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='test', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
