# Generated by Django 3.2.15 on 2022-09-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firingtickets', '0003_auto_20220921_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='membership',
            field=models.CharField(choices=[('Mbr', 'Member'), ('Sdt', 'Student'), ('Gst', 'Guest')], default='Member', max_length=32),
        ),
    ]
