# Generated by Django 3.2.15 on 2022-09-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firingtickets', '0004_project_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='membership',
            field=models.CharField(choices=[('Member', 'Member'), ('Student', 'Student'), ('Guest', 'Guest')], default='Member', max_length=32),
        ),
    ]
