# Generated by Django 3.2.15 on 2022-09-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firingtickets', '0005_alter_project_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='potter',
        ),
    ]
