# Generated by Django 3.2.15 on 2022-09-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firingtickets', '0006_remove_project_potter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='width',
            field=models.IntegerField(),
        ),
    ]
