# Generated by Django 3.2.15 on 2023-07-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firingtickets', '0008_auto_20230708_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
