# Generated by Django 3.2.15 on 2023-07-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firingtickets', '0007_auto_20220922_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='first_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='project',
            name='last_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
